class CurrencyInfo
  attr_accessor :code, :rate
  
  @@countries_map = {
    'AFN' => { 'name' => "Afghanistan", 'code' => 'AF' },
    'AFA' => { 'name' => "Afghanistan", 'code' => 'AF' },
    'ALK' => { 'name' => "Albania", 'code' => 'AL' },
    'ALL' => { 'name' => "Albania", 'code' => 'AL' },
    'DZD' => { 'name' => "Algeria", 'code' => 'DZ' },
    'USD' => { 'name' => "American Samoa", 'code' => 'AS' },
    'ADF' => { 'name' => "Andorra", 'code' => 'AD' },
    'ADP' => { 'name' => "Andorra", 'code' => 'AD' },
    'EUR' => { 'name' => "Andorra", 'code' => 'AD' },
    'AOR' => { 'name' => "Angola", 'code' => 'AO' },
    'AON' => { 'name' => "Angola", 'code' => 'AO' },
    'AOA' => { 'name' => "Angola", 'code' => 'AO' },
    'XCD' => { 'name' => "Anguilla", 'code' => 'AI' },
    'XCD' => { 'name' => "Antigua and Barbuda", 'code' => 'AG' },
    'ARA' => { 'name' => "Argentina", 'code' => 'AR' },
    'ARS' => { 'name' => "Argentina", 'code' => 'AR' },
    'ARL' => { 'name' => "Argentina", 'code' => 'AR' },
    'ARM' => { 'name' => "Argentina", 'code' => 'AR' },
    'ARP' => { 'name' => "Argentina", 'code' => 'AR' },
    'AMD' => { 'name' => "Armenia", 'code' => 'AM' },
    'AWG' => { 'name' => "Aruba", 'code' => 'AW' },
    'AUD' => { 'name' => "Australia", 'code' => 'AU' },
    'ATS' => { 'name' => "Austria", 'code' => 'AT' },
    'EUR' => { 'name' => "Austria", 'code' => 'AT' },
    'AZM' => { 'name' => "Azerbaijan", 'code' => 'AZ' },
    'AZN' => { 'name' => "Azerbaijan", 'code' => 'AZ' },
    'BSD' => { 'name' => "Bahamas", 'code' => 'BS' },
    'BHD' => { 'name' => "Bahrain", 'code' => 'BH' },
    'BDT' => { 'name' => "Bangladesh", 'code' => 'BD' },
    'BBD' => { 'name' => "Barbados", 'code' => 'BB' },
    'BYR' => { 'name' => "Belarus", 'code' => 'BY' },
    'BEC' => { 'name' => "Belgium", 'code' => 'BE' },
    'BEF' => { 'name' => "Belgium", 'code' => 'BE' },
    'BEL' => { 'name' => "Belgium", 'code' => 'BE' },
    'EUR' => { 'name' => "Belgium", 'code' => 'BE' },
    'BZD' => { 'name' => "Belize", 'code' => 'BZ' },
    'XOF' => { 'name' => "Benin", 'code' => 'BJ' },
    'BMD' => { 'name' => "Bermuda", 'code' => 'BM' },
    'INR' => { 'name' => "Bhutan", 'code' => 'BT' },
    'BTN' => { 'name' => "Bhutan", 'code' => 'BT' },
    'BOP' => { 'name' => "Bolivia, Plurinational State Of", 'code' => 'BO' },
    'BOB' => { 'name' => "Bolivia, Plurinational State Of", 'code' => 'BO' },
    'BOV' => { 'name' => "Bolivia, Plurinational State Of", 'code' => 'BO' },
    'USD' => { 'name' => "Bonaire, Sint Eustatius and Saba", 'code' => 'BQ' },
    'BAM' => { 'name' => "Bosnia and Herzegovina", 'code' => 'BA' },
    'BWP' => { 'name' => "Botswana", 'code' => 'BW' },
    'NOK' => { 'name' => "Bouvet Island", 'code' => 'BV' },
    'BRC' => { 'name' => "Brazil", 'code' => 'BR' },
    'BRB' => { 'name' => "Brazil", 'code' => 'BR' },
    'BRL' => { 'name' => "Brazil", 'code' => 'BR' },
    'USD' => { 'name' => "British Indian Ocean Territory", 'code' => 'IO' },
    'BND' => { 'name' => "Brunei Darussalam", 'code' => 'BN' },
    'BGN' => { 'name' => "Bulgaria", 'code' => 'BG' },
    'BGJ' => { 'name' => "Bulgaria", 'code' => 'BG' },
    'BGK' => { 'name' => "Bulgaria", 'code' => 'BG' },
    'BGL' => { 'name' => "Bulgaria", 'code' => 'BG' },
    'XOF' => { 'name' => "Burkina Faso", 'code' => 'BF' },
    'BIF' => { 'name' => "Burundi", 'code' => 'BI' },
    'KHR' => { 'name' => "Cambodia", 'code' => 'KH' },
    'XAF' => { 'name' => "Cameroon", 'code' => 'CM' },
    'CAD' => { 'name' => "Canada", 'code' => 'CA' },
    'CVE' => { 'name' => "Cape Verde", 'code' => 'CV' },
    'KYD' => { 'name' => "Cayman Islands", 'code' => 'KY' },
    'XAF' => { 'name' => "Central African Republic", 'code' => 'CF' },
    'XAF' => { 'name' => "Chad", 'code' => 'TD' },
    'CLP' => { 'name' => "Chile", 'code' => 'CL' },
    'CLF' => { 'name' => "Chile", 'code' => 'CL' },
    'CNX' => { 'name' => "China", 'code' => 'CN' },
    'CNY' => { 'name' => "China", 'code' => 'CN' },
    'AUD' => { 'name' => "Christmas Island", 'code' => 'CX' },
    'AUD' => { 'name' => "Cocos (Keeling) Islands", 'code' => 'CC' },
    'COP' => { 'name' => "Colombia", 'code' => 'CO' },
    'COU' => { 'name' => "Colombia", 'code' => 'CO' },
    'KMF' => { 'name' => "Comoros", 'code' => 'KM' },
    'XAF' => { 'name' => "Congo", 'code' => 'CG' },
    'CDF' => { 'name' => "Congo, The Democratic Republic Of The", 'code' => 'CD' },
    'NZD' => { 'name' => "Cook Islands", 'code' => 'CK' },
    'CRC' => { 'name' => "Costa Rica", 'code' => 'CR' },
    'HRK' => { 'name' => "Croatia", 'code' => 'HR' },
    'CUP' => { 'name' => "Cuba", 'code' => 'CU' },
    'CUC' => { 'name' => "Cuba", 'code' => 'CU' },
    'ANG' => { 'name' => "Curaçao", 'code' => 'CW' },
    'CYP' => { 'name' => "Cyprus", 'code' => 'CY' },
    'EUR' => { 'name' => "Cyprus", 'code' => 'CY' },
    'CZK' => { 'name' => "Czech Republic", 'code' => 'CZ' },
    'CSK' => { 'name' => "Czechoslovak Socialist Republic", 'code' => 'CS' },
    'CSJ' => { 'name' => "Czechoslovak Socialist Republic", 'code' => 'CS' },
    'XOF' => { 'name' => "Côte D\'Ivoire", 'code' => 'CI' },
    'DKK' => { 'name' => "Denmark", 'code' => 'DK' },
    'DJF' => { 'name' => "Djibouti", 'code' => 'DJ' },
    'XCD' => { 'name' => "Dominica", 'code' => 'DM' },
    'DOP' => { 'name' => "Dominican Republic", 'code' => 'DO' },
    'ECS' => { 'name' => "Ecuador", 'code' => 'EC' },
    'USD' => { 'name' => "Ecuador", 'code' => 'EC' },
    'EGP' => { 'name' => "Egypt", 'code' => 'EG' },
    'SVC' => { 'name' => "El Salvador", 'code' => 'SV' },
    'SVC' => { 'name' => "El Salvador", 'code' => 'SV' },
    'USD' => { 'name' => "El Salvador", 'code' => 'SV' },
    'XAF' => { 'name' => "Equatorial Guinea", 'code' => 'GQ' },
    'EQE' => { 'name' => "Equatorial Guinea", 'code' => 'GQ' },
    'ERN' => { 'name' => "Eritrea", 'code' => 'ER' },
    'EUR' => { 'name' => "Estonia", 'code' => 'EE' },
    'EEK' => { 'name' => "Estonia", 'code' => 'EE' },
    'ETB' => { 'name' => "Ethiopia", 'code' => 'ET' },
    'FKP' => { 'name' => "Falkland Islands  (Malvinas)", 'code' => 'FK' },
    'DKK' => { 'name' => "Faroe Islands", 'code' => 'FO' },
    'FJD' => { 'name' => "Fiji", 'code' => 'FJ' },
    'EUR' => { 'name' => "Finland", 'code' => 'FI' },
    'FIM' => { 'name' => "Finland", 'code' => 'FI' },
    'EUR' => { 'name' => "France", 'code' => 'FR' },
    'FRF' => { 'name' => "France", 'code' => 'FR' },
    'XFO' => { 'name' => "France", 'code' => 'FR' },
    'EUR' => { 'name' => "French Guiana", 'code' => 'GF' },
    'XPF' => { 'name' => "French Polynesia", 'code' => 'PF' },
    'EUR' => { 'name' => "French Southern Territories", 'code' => 'TF' },
    'XAF' => { 'name' => "Gabon", 'code' => 'GA' },
    'GMD' => { 'name' => "Gambia", 'code' => 'GM' },
    'GEL' => { 'name' => "Georgia", 'code' => 'GE' },
    'DDM' => { 'name' => "German Democratic Republic", 'code' => 'DD' },
    'DEM' => { 'name' => "Germany", 'code' => 'DE' },
    'EUR' => { 'name' => "Germany", 'code' => 'DE' },
    'GHS' => { 'name' => "Ghana", 'code' => 'GH' },
    'GHC' => { 'name' => "Ghana", 'code' => 'GH' },
    'GIP' => { 'name' => "Gibraltar", 'code' => 'GI' },
    'EUR' => { 'name' => "Greece", 'code' => 'GR' },
    'GRD' => { 'name' => "Greece", 'code' => 'GR' },
    'DKK' => { 'name' => "Greenland", 'code' => 'GL' },
    'XCD' => { 'name' => "Grenada", 'code' => 'GD' },
    'EUR' => { 'name' => "Guadeloupe", 'code' => 'GP' },
    'USD' => { 'name' => "Guam", 'code' => 'GU' },
    'GTQ' => { 'name' => "Guatemala", 'code' => 'GT' },
    'GBP' => { 'name' => "Guernsey", 'code' => 'GG' },
    'GNF' => { 'name' => "Guinea", 'code' => 'GN' },
    'GNE' => { 'name' => "Guinea", 'code' => 'GN' },
    'XOF' => { 'name' => "Guinea-Bissau", 'code' => 'GW' },
    'GWP' => { 'name' => "Guinea-Bissau", 'code' => 'GW' },
    'GYD' => { 'name' => "Guyana", 'code' => 'GY' },
    'HTG' => { 'name' => "Haiti", 'code' => 'HT' },
    'USD' => { 'name' => "Haiti", 'code' => 'HT' },
    'AUD' => { 'name' => "Heard Island and McDonald Islands", 'code' => 'HM' },
    'EUR' => { 'name' => "Holy See (Vatican City State)", 'code' => 'VA' },
    'HNL' => { 'name' => "Honduras", 'code' => 'HN' },
    'HKD' => { 'name' => "Hong Kong", 'code' => 'HK' },
    'HUF' => { 'name' => "Hungary", 'code' => 'HU' },
    'ISK' => { 'name' => "Iceland", 'code' => 'IS' },
    'ISJ' => { 'name' => "Iceland", 'code' => 'IS' },
    'INR' => { 'name' => "India", 'code' => 'IN' },
    'IDR' => { 'name' => "Indonesia", 'code' => 'ID' },
    'IRR' => { 'name' => "Iran, Islamic Republic Of", 'code' => 'IR' },
    'IQD' => { 'name' => "Iraq", 'code' => 'IQ' },
    'EUR' => { 'name' => "Ireland", 'code' => 'IE' },
    'IEP' => { 'name' => "Ireland", 'code' => 'IE' },
    'GBP' => { 'name' => "Isle of Man", 'code' => 'IM' },
    'ILP' => { 'name' => "Israel", 'code' => 'IL' },
    'ILR' => { 'name' => "Israel", 'code' => 'IL' },
    'ILS' => { 'name' => "Israel", 'code' => 'IL' },
    'EUR' => { 'name' => "Italy", 'code' => 'IT' },
    'ITL' => { 'name' => "Italy", 'code' => 'IT' },
    'JMD' => { 'name' => "Jamaica", 'code' => 'JM' },
    'JPY' => { 'name' => "Japan", 'code' => 'JP' },
    'GBP' => { 'name' => "Jersey", 'code' => 'JE' },
    'JOD' => { 'name' => "Jordan", 'code' => 'JO' },
    'KZT' => { 'name' => "Kazakhstan", 'code' => 'KZ' },
    'KES' => { 'name' => "Kenya", 'code' => 'KE' },
    'AUD' => { 'name' => "Kiribati", 'code' => 'KI' },
    'KPW' => { 'name' => "Korea, Democratic People\'s Republic Of", 'code' => 'KP' },
    'KRW' => { 'name' => "Korea, Republic of", 'code' => 'KR' },
    'KWD' => { 'name' => "Kuwait", 'code' => 'KW' },
    'KGS' => { 'name' => "Kyrgyzstan", 'code' => 'KG' },
    'LAK' => { 'name' => "Lao People\'s Democratic Republic", 'code' => 'LA' },
    'LAJ' => { 'name' => "Lao People\'s Democratic Republic", 'code' => 'LA' },
    'LVL' => { 'name' => "Latvia", 'code' => 'LV' },
    'LBP' => { 'name' => "Lebanon", 'code' => 'LB' },
    'LSL' => { 'name' => "Lesotho", 'code' => 'LS' },
    'ZAR' => { 'name' => "Lesotho", 'code' => 'LS' },
    'LRD' => { 'name' => "Liberia", 'code' => 'LR' },
    'LYD' => { 'name' => "Libya", 'code' => 'LY' },
    'CHF' => { 'name' => "Liechtenstein", 'code' => 'LI' },
    'LTL' => { 'name' => "Lithuania", 'code' => 'LT' },
    'EUR' => { 'name' => "Luxembourg", 'code' => 'LU' },
    'LUF' => { 'name' => "Luxembourg", 'code' => 'LU' },
    'MOP' => { 'name' => "Macao", 'code' => 'MO' },
    'MKD' => { 'name' => "Macedonia, the Former Yugoslav Republic Of", 'code' => 'MK' },
    'MKN' => { 'name' => "Macedonia, the Former Yugoslav Republic Of", 'code' => 'MK' },
    'MGA' => { 'name' => "Madagascar", 'code' => 'MG' },
    'MGF' => { 'name' => "Madagascar", 'code' => 'MG' },
    'MWK' => { 'name' => "Malawi", 'code' => 'MW' },
    'MYR' => { 'name' => "Malaysia", 'code' => 'MY' },
    'MVQ' => { 'name' => "Maldives", 'code' => 'MV' },
    'MVR' => { 'name' => "Maldives", 'code' => 'MV' },
    'XOF' => { 'name' => "Mali", 'code' => 'ML' },
    'MAF' => { 'name' => "Mali", 'code' => 'ML' },
    'EUR' => { 'name' => "Malta", 'code' => 'MT' },
    'MTL' => { 'name' => "Malta", 'code' => 'MT' },
    'USD' => { 'name' => "Marshall Islands", 'code' => 'MH' },
    'EUR' => { 'name' => "Martinique", 'code' => 'MQ' },
    'MRO' => { 'name' => "Mauritania", 'code' => 'MR' },
    'MUR' => { 'name' => "Mauritius", 'code' => 'MU' },
    'EUR' => { 'name' => "Mayotte", 'code' => 'YT' },
    'MXP' => { 'name' => "Mexico", 'code' => 'MX' },
    'MXN' => { 'name' => "Mexico", 'code' => 'MX' },
    'MXV' => { 'name' => "Mexico", 'code' => 'MX' },
    'USD' => { 'name' => "Micronesia, Federated States Of", 'code' => 'FM' },
    'MDL' => { 'name' => "Moldova, Republic of", 'code' => 'MD' },
    'EUR' => { 'name' => "Monaco", 'code' => 'MC' },
    'MCF' => { 'name' => "Monaco", 'code' => 'MC' },
    'MNT' => { 'name' => "Mongolia", 'code' => 'MN' },
    'EUR' => { 'name' => "Montenegro", 'code' => 'ME' },
    'XCD' => { 'name' => "Montserrat", 'code' => 'MS' },
    'MAD' => { 'name' => "Morocco", 'code' => 'MA' },
    'MZM' => { 'name' => "Mozambique", 'code' => 'MZ' },
    'MZN' => { 'name' => "Mozambique", 'code' => 'MZ' },
    'MMK' => { 'name' => "Myanmar", 'code' => 'MM' },
    'NAD' => { 'name' => "Namibia", 'code' => 'NA' },
    'ZAR' => { 'name' => "Namibia", 'code' => 'NA' },
    'AUD' => { 'name' => "Nauru", 'code' => 'NR' },
    'NPR' => { 'name' => "Nepal", 'code' => 'NP' },
    'EUR' => { 'name' => "Netherlands", 'code' => 'NL' },
    'NLG' => { 'name' => "Netherlands", 'code' => 'NL' },
    'ANG' => { 'name' => "Netherlands Antilles", 'code' => 'AN' },
    'XPF' => { 'name' => "New Caledonia", 'code' => 'NC' },
    'NZD' => { 'name' => "New Zealand", 'code' => 'NZ' },
    'NIO' => { 'name' => "Nicaragua", 'code' => 'NI' },
    'XOF' => { 'name' => "Niger", 'code' => 'NE' },
    'NGN' => { 'name' => "Nigeria", 'code' => 'NG' },
    'NZD' => { 'name' => "Niue", 'code' => 'NU' },
    'AUD' => { 'name' => "Norfolk Island", 'code' => 'NF' },
    'USD' => { 'name' => "Northern Mariana Islands", 'code' => 'MP' },
    'NOK' => { 'name' => "Norway", 'code' => 'NO' },
    'OMR' => { 'name' => "Oman", 'code' => 'OM' },
    'PKR' => { 'name' => "Pakistan", 'code' => 'PK' },
    'USD' => { 'name' => "Palau", 'code' => 'PW' },
    'PAB' => { 'name' => "Panama", 'code' => 'PA' },
    'PAB' => { 'name' => "Panama", 'code' => 'PA' },
    'USD' => { 'name' => "Panama", 'code' => 'PA' },
    'USD' => { 'name' => "Panama", 'code' => 'PA' },
    'PGK' => { 'name' => "Papua New Guinea", 'code' => 'PG' },
    'PYG' => { 'name' => "Paraguay", 'code' => 'PY' },
    'YDD' => { 'name' => "People\'s Democratic Republic of Yemen", 'code' => 'YD' },
    'PEN' => { 'name' => "Peru", 'code' => 'PE' },
    'PEI' => { 'name' => "Peru", 'code' => 'PE' },
    'PEH' => { 'name' => "Peru", 'code' => 'PE' },
    'PHP' => { 'name' => "Philippines", 'code' => 'PH' },
    'NZD' => { 'name' => "Pitcairn", 'code' => 'PN' },
    'PLZ' => { 'name' => "Poland", 'code' => 'PL' },
    'PLN' => { 'name' => "Poland", 'code' => 'PL' },
    'EUR' => { 'name' => "Portugal", 'code' => 'PT' },
    'PTE' => { 'name' => "Portugal", 'code' => 'PT' },
    'TPE' => { 'name' => "Portugal", 'code' => 'PT' },
    'USD' => { 'name' => "Puerto Rico", 'code' => 'PR' },
    'QAR' => { 'name' => "Qatar", 'code' => 'QA' },
    'RON' => { 'name' => "Romania", 'code' => 'RO' },
    'ROL' => { 'name' => "Romania", 'code' => 'RO' },
    'ROK' => { 'name' => "Romania", 'code' => 'RO' },
    'RUB' => { 'name' => "Russian Federation", 'code' => 'RU' },
    'RWF' => { 'name' => "Rwanda", 'code' => 'RW' },
    'EUR' => { 'name' => "Réunion", 'code' => 'RE' },
    'EUR' => { 'name' => "Saint Barthélemy", 'code' => 'BL' },
    'SHP' => { 'name' => "Saint Helena, Ascension and Tristan Da Cunha", 'code' => 'SH' },
    'XCD' => { 'name' => "Saint Kitts And Nevis", 'code' => 'KN' },
    'XCD' => { 'name' => "Saint Lucia", 'code' => 'LC' },
    'EUR' => { 'name' => "Saint Martin (French Part)", 'code' => 'MF' },
    'EUR' => { 'name' => "Saint Pierre And Miquelon", 'code' => 'PM' },
    'XCD' => { 'name' => "Saint Vincent And The Grenadines", 'code' => 'VC' },
    'WST' => { 'name' => "Samoa", 'code' => 'WS' },
    'EUR' => { 'name' => "San Marino", 'code' => 'SM' },
    'STD' => { 'name' => "Sao Tome and Principe", 'code' => 'ST' },
    'SAR' => { 'name' => "Saudi Arabia", 'code' => 'SA' },
    'XOF' => { 'name' => "Senegal", 'code' => 'SN' },
    'CSD' => { 'name' => "Serbia", 'code' => 'RS' },
    'RSD' => { 'name' => "Serbia", 'code' => 'RS' },
    'SCR' => { 'name' => "Seychelles", 'code' => 'SC' },
    'SLL' => { 'name' => "Sierra Leone", 'code' => 'SL' },
    'SGD' => { 'name' => "Singapore", 'code' => 'SG' },
    'ANG' => { 'name' => "Sint Maarten (Dutch part)", 'code' => 'SX' },
    'EUR' => { 'name' => "Slovakia", 'code' => 'SK' },
    'SKK' => { 'name' => "Slovakia", 'code' => 'SK' },
    'EUR' => { 'name' => "Slovenia", 'code' => 'SI' },
    'SIT' => { 'name' => "Slovenia", 'code' => 'SI' },
    'SBD' => { 'name' => "Solomon Islands", 'code' => 'SB' },
    'SOS' => { 'name' => "Somalia", 'code' => 'SO' },
    'ZAR' => { 'name' => "South Africa", 'code' => 'ZA' },
    'ZAL' => { 'name' => "South Africa", 'code' => 'ZA' },
    'SSP' => { 'name' => "South Sudan", 'code' => 'SS' },
    'EUR' => { 'name' => "Spain", 'code' => 'ES' },
    'ESP' => { 'name' => "Spain", 'code' => 'ES' },
    'ESA' => { 'name' => "Spain", 'code' => 'ES' },
    'ESB' => { 'name' => "Spain", 'code' => 'ES' },
    'LKR' => { 'name' => "Sri Lanka", 'code' => 'LK' },
    'SDD' => { 'name' => "Sudan", 'code' => 'SD' },
    'SDG' => { 'name' => "Sudan", 'code' => 'SD' },
    'SDP' => { 'name' => "Sudan", 'code' => 'SD' },
    'SRD' => { 'name' => "Suriname", 'code' => 'SR' },
    'SRG' => { 'name' => "Suriname", 'code' => 'SR' },
    'NOK' => { 'name' => "Svalbard And Jan Mayen", 'code' => 'SJ' },
    'SZL' => { 'name' => "Swaziland", 'code' => 'SZ' },
    'SEK' => { 'name' => "Sweden", 'code' => 'SE' },
    'CHF' => { 'name' => "Switzerland", 'code' => 'CH' },
    'CHE' => { 'name' => "Switzerland", 'code' => 'CH' },
    'CHW' => { 'name' => "Switzerland", 'code' => 'CH' },
    'SYP' => { 'name' => "Syrian Arab Republic", 'code' => 'SY' },
    'TWD' => { 'name' => "Taiwan, Province Of China", 'code' => 'TW' },
    'TJS' => { 'name' => "Tajikistan", 'code' => 'TJ' },
    'TJR' => { 'name' => "Tajikistan", 'code' => 'TJ' },
    'TZS' => { 'name' => "Tanzania, United Republic of", 'code' => 'TZ' },
    'THB' => { 'name' => "Thailand", 'code' => 'TH' },
    'USD' => { 'name' => "Timor-Leste", 'code' => 'TL' },
    'XOF' => { 'name' => "Togo", 'code' => 'TG' },
    'NZD' => { 'name' => "Tokelau", 'code' => 'TK' },
    'TOP' => { 'name' => "Tonga", 'code' => 'TO' },
    'TTD' => { 'name' => "Trinidad and Tobago", 'code' => 'TT' },
    'TND' => { 'name' => "Tunisia", 'code' => 'TN' },
    'TRY' => { 'name' => "Turkey", 'code' => 'TR' },
    'TRL' => { 'name' => "Turkey", 'code' => 'TR' },
    'TMM' => { 'name' => "Turkmenistan", 'code' => 'TM' },
    'TMT' => { 'name' => "Turkmenistan", 'code' => 'TM' },
    'USD' => { 'name' => "Turks and Caicos Islands", 'code' => 'TC' },
    'AUD' => { 'name' => "Tuvalu", 'code' => 'TV' },
    'RUR' => { 'name' => "U.S.S.R.", 'code' => 'SU' },
    'SUR' => { 'name' => "U.S.S.R.", 'code' => 'SU' },
    'UGX' => { 'name' => "Uganda", 'code' => 'UG' },
    'UGS' => { 'name' => "Uganda", 'code' => 'UG' },
    'UAH' => { 'name' => "Ukraine", 'code' => 'UA' },
    'UAK' => { 'name' => "Ukraine", 'code' => 'UA' },
    'AED' => { 'name' => "United Arab Emirates", 'code' => 'AE' },
    'GBP' => { 'name' => "United Kingdom", 'code' => 'GB' },
    'USD' => { 'name' => "United States", 'code' => 'US' },
    'USN' => { 'name' => "United States", 'code' => 'US' },
    'USS' => { 'name' => "United States", 'code' => 'US' },
    'USD' => { 'name' => "United States Minor Outlying Islands", 'code' => 'UM' },
    'UYU' => { 'name' => "Uruguay", 'code' => 'UY' },
    'UYN' => { 'name' => "Uruguay", 'code' => 'UY' },
    'UYI' => { 'name' => "Uruguay", 'code' => 'UY' },
    'UZS' => { 'name' => "Uzbekistan", 'code' => 'UZ' },
    'VUV' => { 'name' => "Vanuatu", 'code' => 'VU' },
    'VEF' => { 'name' => "Venezuela, Bolivarian Republic of", 'code' => 'VE' },
    'VEB' => { 'name' => "Venezuela, Bolivarian Republic of", 'code' => 'VE' },
    'VND' => { 'name' => "Viet Nam", 'code' => 'VN' },
    'VNC' => { 'name' => "Viet Nam", 'code' => 'VN' },
    'USD' => { 'name' => "Virgin Islands, British", 'code' => 'VG' },
    'USD' => { 'name' => "Virgin Islands, U.S.", 'code' => 'VI' },
    'XPF' => { 'name' => "Wallis and Futuna", 'code' => 'WF' },
    'MAD' => { 'name' => "Western Sahara", 'code' => 'EH' },
    'YER' => { 'name' => "Yemen", 'code' => 'YE' },
    'YUD' => { 'name' => "Yugoslavia", 'code' => 'YU' },
    'YUM' => { 'name' => "Yugoslavia", 'code' => 'YU' },
    'ZRN' => { 'name' => "Zaire", 'code' => 'ZR' },
    'ZRZ' => { 'name' => "Zaire", 'code' => 'ZR' },
    'ZMK' => { 'name' => "Zambia", 'code' => 'ZM' },
    'ZWL' => { 'name' => "Zimbabwe", 'code' => 'ZW' },
    'ZWD' => { 'name' => "Zimbabwe", 'code' => 'ZW' },
    'ZWC' => { 'name' => "Zimbabwe", 'code' => 'ZW' },
    'EUR' => { 'name' => "Åland Islands", 'code' => 'AX' }
  }
  
  def initialize(code, rate)
    @code = code
    @rate = rate
  end
  
  def name
    @@countries_map.has_key?(@code) ? @@countries_map[@code]['name'] : @code
  end
  
  def country_code
    @@countries_map[@code]['code'] if @@countries_map.has_key?(@code)
  end
end